export const PHONE_LOGIN_OTP_LENGTH = 4
export const PHONE_LOGIN_OTP_LABEL = `${PHONE_LOGIN_OTP_LENGTH}-digit OTP`
export const PHONE_LOGIN_OTP_INPUT_PATTERN = `[0-9]{${PHONE_LOGIN_OTP_LENGTH}}`
export const PHONE_LOGIN_OTP_DIGITS_REGEX = new RegExp(
  `^\\d{${PHONE_LOGIN_OTP_LENGTH}}$`
)
export const PHONE_LOGIN_OTP_MIN = 10 ** (PHONE_LOGIN_OTP_LENGTH - 1)
export const PHONE_LOGIN_OTP_MAX_EXCLUSIVE = 10 ** PHONE_LOGIN_OTP_LENGTH
