export const MIN_SEARCH_QUERY_LENGTH = 2
export const SEARCH_DEBOUNCE_MS = 300
export const SEARCH_DEFAULT_PRODUCT_LIMIT = 6
export const SEARCH_DEFAULT_TAXONOMY_LIMIT = 5
export const SEARCH_MAX_PRODUCT_LIMIT = 10
export const SEARCH_MAX_TAXONOMY_LIMIT = 10
export const SEARCH_MAX_QUERY_LENGTH = 80
